// components/forms/project-options.ts
export const TAG_OPTIONS = [
  { label: "Inteligencia Artificial", value: "ia" },
  { label: "Web", value: "web" },
  { label: "Educación", value: "educacion" },
  { label: "Salud", value: "salud" },
  { label: "Finanzas", value: "finanzas" },
  { label: "Marketing", value: "marketing" },
  { label: "E-commerce", value: "ecommerce" },
  { label: "Juegos", value: "juegos" },
  { label: "Blockchain", value: "blockchain" },
  { label: "IoT", value: "iot" },
  { label: "Robótica", value: "robotica" },
  { label: "Sostenibilidad", value: "sostenibilidad" },
  { label: "Seguridad", value: "seguridad" },
  { label: "Big Data", value: "bigdata" },
  { label: "Desarrollo Móvil", value: "movil" },
];

export const TOOL_OPTIONS = [
  { label: "React", value: "react" },
  { label: "Python", value: "python" },
  { label: "TensorFlow", value: "tensorflow" },
  { label: "Node.js", value: "node" },
  { label: "Docker", value: "docker" },
  { label: "AWS", value: "aws" },
  { label: "Azure", value: "azure" },
  { label: "Google Cloud", value: "gcp" },
  { label: "PostgreSQL", value: "postgresql" },
  { label: "MySQL", value: "mysql" },
  { label: "MongoDB", value: "mongodb" },
  { label: "Git", value: "git" },
  { label: "Figma", value: "figma" },
  { label: "Jira", value: "jira" },
];