export const TAG_OPTIONS = [
  { label: "Inteligencia Artificial", value: "ia" },
  { label: "Web", value: "web" },
  { label: "Educación", value: "educacion" },
  { label: "Salud", value: "salud" },
  { label: "Finanzas", value: "finanzas" },
  { label: "Marketing", value: "marketing" },
  { label: "E-commerce", value: "ecommerce" },
  { label: "Juegos", value: "juegos" },
  { label: "Blockchain", value: "blockchain" },
  { label: "IoT", value: "iot" },
  { label: "Robótica", value: "robotica" },
  { label: "Sostenibilidad", value: "sostenibilidad" },
  { label: "Seguridad", value: "seguridad" },
  { label: "Big Data", value: "bigdata" },
  { label: "Desarrollo Móvil", value: "movil" },
  { label: "Diseño UX/UI", value: "uxui" },
  { label: "Automatización", value: "automatizacion" },
  { label: "Deportes", value: "deportes" },
  { label: "Arte y Cultura", value: "artecultura" },
];

export const TOOL_OPTIONS = [
  { label: "React", value: "react" },
  { label: "Python", value: "python" },
  { label: "TensorFlow", value: "tensorflow" },
  { label: "Node.js", value: "nodejs" },
  { label: "Docker", value: "docker" },
  { label: "Azure", value: "azure" },
  { label: "Angular", value: "angular" }, 
  { label: "PostgreSQL", value: "postgresql" },
  { label: "MySQL", value: "mysql" },
  { label: "MongoDB", value: "mongodb" },
  { label: "Git", value: "git" },
  { label: "Figma", value: "figma" },
  { label: "Jira", value: "jira" },
  { label: "Vue.js", value: "vue" },
  { label: "Java", value: "java" },
  { label: "PHP", value: "php" },
  { label: "Kotlin", value: "kotlin" },
  { label: "JavaScript", value: "js" },
  { label: "CSS", value: "css" },
  { label: "HTML", value: "html" },
  { label: "NestJS", value: "nestjs" },
  { label: "Next.js", value: "nextjs" },
  { label: "TypeScript", value: "ts" },
];